CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    message VARCHAR(500) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    project_id BIGINT,
    task_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notif_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notif_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_notif_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT chk_notifications_type CHECK (
        type IN (
            'TASK_ASSIGNED',
            'SUBMISSION_SUBMITTED',
            'CHANGES_REQUESTED',
            'TASK_APPROVED'
        )
    )
);

--Index quan trọng nhất: query "lấy thông báo chưa đọc của 1 user, mới nhất trước"
CREATE INDEX idx_notifications_recipient_created_at
    ON notifications (recipient_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_unread
    ON notifications (recipient_id, created_at DESC)
    WHERE is_read = FALSE;