CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_projects_date_range CHECK (start_date <= end_date)
);

CREATE INDEX idx_projects_user_id ON projects (user_id);