ALTER TABLE project_members
    DROP CONSTRAINT chk_project_members_role;

UPDATE project_members
SET role = 'MANAGER'
WHERE role = 'ADMIN';

ALTER TABLE project_members
    ADD CONSTRAINT chk_project_members_role
    CHECK (role IN ('OWNER', 'MANAGER', 'MEMBER', 'VIEWER'));

ALTER TABLE tasks
        DROP CONSTRAINT IF EXISTS chk_tasks_status;

-- TODO BUSINESS RULE: BLOCKED is not part of the agreed workflow, but silently
-- converting it would invent business meaning. Stop migration when legacy rows
-- exist so their target status can be decided explicitly before retrying V6.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM tasks WHERE status = 'BLOCKED') THEN
        RAISE EXCEPTION
            'Cannot remove BLOCKED task status: migrate existing BLOCKED tasks explicitly before V6';
    END IF;
END
$$;

ALTER TABLE tasks
    ADD CONSTRAINT chk_tasks_status
    CHECK (status IN ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'CHANGES_REQUESTED', 'DONE'));

CREATE TABLE task_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    assignee_id BIGINT NOT NULL,
    assigned_by_id BIGINT,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    assigned_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6),
    CONSTRAINT fk_task_assignments_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignments_assignee
        FOREIGN KEY (assignee_id) REFERENCES project_members (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignments_assigned_by
        FOREIGN KEY (assigned_by_id) REFERENCES project_members (id) ON DELETE SET NULL,
    CONSTRAINT chk_task_assignments_type
        CHECK (type IN ('CLAIMED', 'ASSIGNED')),
    CONSTRAINT chk_task_assignments_status
        CHECK (status IN ('ACTIVE', 'CANCELLED')),
    CONSTRAINT chk_task_assignments_actor
        CHECK (
            (type = 'CLAIMED' AND assigned_by_id IS NULL)
            OR type = 'ASSIGNED'
        ),
    CONSTRAINT chk_task_assignments_end_time
        CHECK (
            (status = 'ACTIVE' AND ended_at IS NULL)
            OR (status = 'CANCELLED' AND ended_at IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uk_task_assignments_one_active
    ON task_assignments (task_id)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_task_assignments_assignee_status
    ON task_assignments (assignee_id, status);

CREATE TABLE task_acceptance_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    satisfied BOOLEAN NOT NULL DEFAULT FALSE,
    position INTEGER NOT NULL,
    CONSTRAINT fk_task_acceptance_criteria_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT chk_task_acceptance_criteria_position
        CHECK (position >= 0)
);

CREATE INDEX idx_task_acceptance_criteria_task_position
    ON task_acceptance_criteria (task_id, position);

CREATE TABLE task_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    decision VARCHAR(32) NOT NULL,
    message VARCHAR(5000),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_reviews_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_reviews_reviewer
        FOREIGN KEY (reviewer_id) REFERENCES project_members (id) ON DELETE CASCADE,
    CONSTRAINT chk_task_reviews_decision
        CHECK (decision IN ('APPROVED', 'CHANGES_REQUESTED')),
    CONSTRAINT chk_task_reviews_message
        CHECK (
            decision = 'APPROVED'
            OR (message IS NOT NULL AND LENGTH(TRIM(message)) > 0)
        )
);

CREATE INDEX idx_task_reviews_task_created_at
    ON task_reviews (task_id, created_at DESC);
