CREATE TABLE task_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    assignee_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMP(6),
    CONSTRAINT fk_task_submissions_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_submissions_assignee FOREIGN KEY (assignee_id) REFERENCES project_members (id),
    CONSTRAINT uk_task_submissions_task_sequence UNIQUE (task_id, sequence_number),
    CONSTRAINT chk_task_submissions_sequence CHECK (sequence_number > 0),
    CONSTRAINT chk_task_submissions_status CHECK (status IN ('DRAFT', 'SUBMITTED')),
    CONSTRAINT chk_task_submissions_submitted_at CHECK (
        (status = 'DRAFT' AND submitted_at IS NULL)
        OR (status = 'SUBMITTED' AND submitted_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_task_submissions_one_draft
    ON task_submissions (task_id)
    WHERE status = 'DRAFT';

CREATE TABLE task_evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    evidence_type VARCHAR(32) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    url VARCHAR(2048),
    storage_key VARCHAR(1024),
    content_type VARCHAR(255),
    file_size BIGINT,
    upload_status VARCHAR(32),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_evidences_submission FOREIGN KEY (submission_id) REFERENCES task_submissions (id) ON DELETE CASCADE,
    CONSTRAINT chk_task_evidences_type CHECK (evidence_type IN ('UPLOADED_FILE', 'GITHUB_COMMIT', 'GITHUB_PR', 'EXTERNAL_LINK')),
    CONSTRAINT chk_task_evidences_provider CHECK (provider IN ('OBJECT_STORAGE', 'GITHUB', 'GOOGLE_DRIVE', 'GOOGLE_DOCS', 'FIGMA', 'OTHER')),
    CONSTRAINT chk_task_evidences_upload_status CHECK (upload_status IS NULL OR upload_status IN ('PENDING', 'READY', 'FAILED')),
    CONSTRAINT chk_task_evidences_shape CHECK (
        (evidence_type = 'UPLOADED_FILE' AND storage_key IS NOT NULL AND file_size IS NOT NULL AND upload_status IS NOT NULL)
        OR (evidence_type <> 'UPLOADED_FILE' AND url IS NOT NULL AND upload_status IS NULL)
    )
);

CREATE INDEX idx_task_evidences_submission ON task_evidences (submission_id, created_at);

ALTER TABLE task_reviews ADD COLUMN submission_id BIGINT;
ALTER TABLE task_reviews
    ADD CONSTRAINT fk_task_reviews_submission
    FOREIGN KEY (submission_id) REFERENCES task_submissions (id);
CREATE INDEX idx_task_reviews_submission ON task_reviews (submission_id);
