CREATE TABLE user_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_identities_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_identities_provider_subject
        UNIQUE (provider, provider_subject),
    CONSTRAINT uk_user_identities_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT chk_user_identities_provider
        CHECK (provider IN ('GOOGLE'))
);

CREATE INDEX idx_user_identities_user_id ON user_identities (user_id);
